componentScriptContent: 
  - xmlizable: 
    - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      â†’: |
        /*Begin_c8o_AppImport*/
        /*End_c8o_AppImport*/
        /*Begin_c8o_AppDeclaration*/
        	/*End_c8o_AppDeclaration*/
        /*Begin_c8o_AppConstructor*/
        		/*End_c8o_AppConstructor*/
        /*Begin_c8o_AppInitialization*/
                        /* Uncomment the following lines to enable the i18n feature.
                         * You should add a json per language in the assets/i18n folder. */
                        translate.setDefaultLang('en');
                        translate.use(translate.getBrowserLang());
                        
                        /* Uncomment the following lines to enable the custom status bar color. */
                        // statusBar.overlaysWebView(false);
                        // statusBar.backgroundColorByHexString("#000000");
                        // statusBar.styleBlackOpaque();
        			/*End_c8o_AppInitialization*/
        /*Begin_c8o_AppFunction*/
        	/*End_c8o_AppFunction*/
        
tplProjectName: mobilebuilder_tpl_7_7_0
â†“Menu [mobile.components.UIDynamicMenu-1500890597895]: ğŸ— mobileMenus/Menu.yaml
â†“CustomMenu [mobile.components.UIDynamicMenu-1583502473965]: ğŸ— mobileMenus/CustomMenu.yaml
â†“RightMenu [mobile.components.UIDynamicMenu-1579279159205]: ğŸ— mobileMenus/RightMenu.yaml
â†“LeftMenu [mobile.components.UIDynamicMenu-1582887546587]: ğŸ— mobileMenus/LeftMenu.yaml
â†“getPeople [mobile.components.UIActionStack-1579513546604]: ğŸ— mobileSharedActions/getPeople.yaml
â†“KeyPadEntry [mobile.components.UIActionStack-1580307965697]: ğŸ— mobileSharedActions/KeyPadEntry.yaml
â†“SetFocused [mobile.components.UIActionStack-1580307965715]: ğŸ— mobileSharedActions/SetFocused.yaml
â†“Toast [mobile.components.UIActionStack-1580983282970]: ğŸ— mobileSharedActions/Toast.yaml
â†“RefresherMembers [mobile.components.UIActionStack-1582221214219]: ğŸ— mobileSharedActions/RefresherMembers.yaml
â†“openMenu [mobile.components.UIActionStack-1582897048684]: ğŸ— mobileSharedActions/openMenu.yaml
â†“Tooltips [mobile.components.UISharedComponent-1578319869013]: ğŸ— mobileSharedComponents/Tooltips.yaml
â†“KeyPad [mobile.components.UISharedComponent-1580307897891]: ğŸ— mobileSharedComponents/KeyPad.yaml
â†“Footer [mobile.components.UISharedComponent-1582818189622]: ğŸ— mobileSharedComponents/Footer.yaml
â†“Page [mobile.components.PageComponent-1500538678074]: ğŸ— mobilePages/Page.yaml
â†“Page_Customs_Animation [mobile.components.PageComponent-1579103295466]: ğŸ— mobilePages/Page_Customs_Animation.yaml
â†“Page_Customs_Attribute [mobile.components.PageComponent-1576144418242]: ğŸ— mobilePages/Page_Customs_Attribute.yaml
â†“Page_NativeActions_Barcode [mobile.components.PageComponent-1578661180634]: ğŸ— mobilePages/Page_NativeActions_Barcode.yaml
â†“Page_Components_Bars [mobile.components.PageComponent-1579773399612]: ğŸ— mobilePages/Page_Components_Bars.yaml
â†“Page_Buttons_Buttons [mobile.components.PageComponent-1580910018994]: ğŸ— mobilePages/Page_Buttons_Buttons.yaml
â†“Page_NativeActions_Camera [mobile.components.PageComponent-1578655148107]: ğŸ— mobilePages/Page_NativeActions_Camera.yaml
â†“Page_Cards_Cards [mobile.components.PageComponent-1582737918347]: ğŸ— mobilePages/Page_Cards_Cards.yaml
â†“Page_Components_Charts [mobile.components.PageComponent-1579620096330]: ğŸ— mobilePages/Page_Components_Charts.yaml
â†“Page_zHowTos_Chatbot [mobile.components.PageComponent-1580897615447]: ğŸ— mobilePages/Page_zHowTos_Chatbot.yaml
â†“Page_Buttons_Fabs [mobile.components.PageComponent-1580919606453]: ğŸ— mobilePages/Page_Buttons_Fabs.yaml
â†“Page_NativeActions_FileChooser [mobile.components.PageComponent-1578661956046]: ğŸ— mobilePages/Page_NativeActions_FileChooser.yaml
â†“Page_Controls_Finally [mobile.components.PageComponent-1577959939689]: ğŸ— mobilePages/Page_Controls_Finally.yaml
â†“Page_zHowTos_Fingerprint [mobile.components.PageComponent-1579603139459]: ğŸ— mobilePages/Page_zHowTos_Fingerprint.yaml
â†“Page_Forms_Forms [mobile.components.PageComponent-1581527058141]: ğŸ— mobilePages/Page_Forms_Forms.yaml
â†“Page_Customs_Fragment [mobile.components.PageComponent-1579166567728]: ğŸ— mobilePages/Page_Customs_Fragment.yaml
â†“Page_Html_Html [mobile.components.PageComponent-1579875601436]: ğŸ— mobilePages/Page_Html_Html.yaml
â†“Page_zHowTos_IconInput [mobile.components.PageComponent-1576148711969]: ğŸ— mobilePages/Page_zHowTos_IconInput.yaml
â†“Page_zHowTos_KeyPad [mobile.components.PageComponent-1580309028081]: ğŸ— mobilePages/Page_zHowTos_KeyPad.yaml
â†“Page_Lists_Lists [mobile.components.PageComponent-1579283173880]: ğŸ— mobilePages/Page_Lists_Lists.yaml
â†“Page_Menus_Menu [mobile.components.PageComponent-1580914202266]: ğŸ— mobilePages/Page_Menus_Menu.yaml
â†“Page_Actions_modal [mobile.components.PageComponent-1576057381386]: ğŸ— mobilePages/Page_Actions_modal.yaml
â†“Page_Actions_modal1 [mobile.components.PageComponent-1576058487795]: ğŸ— mobilePages/Page_Actions_modal1.yaml
â†“Page_Actions_Pause [mobile.components.PageComponent-1575036271785]: ğŸ— mobilePages/Page_Actions_Pause.yaml
â†“Page_zHowTos_Searchbar [mobile.components.PageComponent-1582623530545]: ğŸ— mobilePages/Page_zHowTos_Searchbar.yaml
â†“Page_Forms_Signature [mobile.components.PageComponent-1574951079411]: ğŸ— mobilePages/Page_Forms_Signature.yaml
â†“Page_NativeActions_SpeechToText [mobile.components.PageComponent-1578662209808]: ğŸ— mobilePages/Page_NativeActions_SpeechToText.yaml
â†“Page_Customs_Style [mobile.components.PageComponent-1579191468247]: ğŸ— mobilePages/Page_Customs_Style.yaml
â†“Page_Components_Tabs [mobile.components.PageComponent-1579531139518]: ğŸ— mobilePages/Page_Components_Tabs.yaml
â†“Page_Components_Tabs_Contacts [mobile.components.PageComponent-1579531610323]: ğŸ— mobilePages/Page_Components_Tabs_Contacts.yaml
â†“Page_Components_Tabs_Map [mobile.components.PageComponent-1579539014048]: ğŸ— mobilePages/Page_Components_Tabs_Map.yaml
â†“Page_Components_Tabs_Chat [mobile.components.PageComponent-1579539073197]: ğŸ— mobilePages/Page_Components_Tabs_Chat.yaml
â†“Page_Customs_Tag [mobile.components.PageComponent-1579257993469]: ğŸ— mobilePages/Page_Customs_Tag.yaml
â†“Page_Customs_Text [mobile.components.PageComponent-1579258848753]: ğŸ— mobilePages/Page_Customs_Text.yaml
â†“Page_NativeActions_TextToSpeech [mobile.components.PageComponent-1578662578479]: ğŸ— mobilePages/Page_NativeActions_TextToSpeech.yaml
â†“Page_Miscellaneous_Tooltip [mobile.components.PageComponent-1576254807835]: ğŸ— mobilePages/Page_Miscellaneous_Tooltip.yaml
â†“Page1 [mobile.components.PageComponent-1580915186349]: ğŸ— mobilePages/Page1.yaml
â†“Page2 [mobile.components.PageComponent-1580915361059]: ğŸ— mobilePages/Page2.yaml
â†“Theme [mobile.components.UITheme-1491635018260]: 
  comment: Global color themes can be customized here
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '// Ionic Variables and Theming. For more info, please see:
          // http://ionicframework.com/docs/v2/theming/ 
          $font-path: "../assets/fonts";
          
          @import "ionic.globals";
          
          
          // Shared Variables
          // --------------------------------------------------
          // To customize the look and feel of this app, you can override
          // the Sass variables found in Ionic''s source scss files.
          // To view all the possible Ionic variables, see:
          // http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/
          
          
          
          
          // Named Color Variables
          // --------------------------------------------------
          // Named colors makes it easy to reuse colors on various components.
          // It''s highly recommended to change the default colors
          // to match your app''s branding. Ionic uses a Sass map of
          // colors so you can add, rename and remove colors as needed.
          // The "primary" color is the only required color in the map.
          
          $colors: (
                  primary:    #387ef5,
                  secondary:  #32db64,
                  danger:     #f53d3d,
                  light:      #f4f4f4,
                  dark:       #222
          );
          
          
          // App iOS Variables
          // --------------------------------------------------
          // iOS only Sass variables can go here
          
          
          
          
          // App Material Design Variables
          // --------------------------------------------------
          // Material Design only Sass variables can go here
          
          
          
          
          // App Windows Variables
          // --------------------------------------------------
          // Windows only Sass variables can go here
          
          
          
          
          // App Theme
          // --------------------------------------------------
          // Ionic apps can have different themes applied, which can
          // then be future customized. This import comes last
          // so that the above variables are used and Ionic''s
          // default are overridden.
          
          @import "ionic.theme.default";
          
          
          // Ionicons
          // --------------------------------------------------
          // The premium icon font for Ionic. For more info, please see:
          // http://ionicframework.com/docs/v2/ionicons/
          
          @import "ionic.ionicons";
          
          
          // Fonts
          // --------------------------------------------------
          
          @import "roboto";
          @import "noto-sans";'
â†“Style [mobile.components.UIStyle-1491635462437]: 
  comment: You can add some global application styles here
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '.content {
          	/* add some styling CSS rules here for the body of your app
          	   for example,
          	 		background-color: your color; 
          	 		background-image: url(some background image);
          	*/
          }
          
          .toolbar-background {
          	/* add some styling CSS rules here for the Headers and Footers
          	   for example,
          	 		background-color: your color; 
          	*/
          }'
â†“ShowGrids [mobile.components.UIStyle-1580914546742]: 
  comment: Enable this to show grid guidelines
  isEnabled: false
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '.content {
          	/* add some styling CSS rules here for the body of your app
          	   for example,
          	 		background-color: your color; 
          	 		background-image: url(some background image);
          	*/
          }
          
          .toolbar-background {
          	/* add some styling CSS rules here for the Headers and Footers
          	   for example,
          	 		background-color: your color; 
          	*/
          }
          
          ion-grid {
          	border: 1px solid red;
          }
          
          ion-row {
          	border: 1px solid blue;
          }
          
          ion-col {
          	border: 1px solid green;
          }'
â†“FullWidthLeftMenu [mobile.components.UIStyle-1582901723172]: 
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          'ion-menu.show-menu#myLeftMenu ~ ion-nav {
              transform: translate3d(100%, 0px, 0px) !important;
              transition: transform 1000ms ease !important;
          }
          
          ion-menu.show-menu#myLeftMenu .menu-inner {
          	width: 100% !important;
          }'